- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 7200 #2 hrs # Bluespace-RoleTime
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 7200 #2 hrs # Bluespace-RoleTime
    - !type:DepartmentTimeRequirement
      department: Security
      time: 7200 #2 hrs # Bluespace-RoleTime
    - !type:DepartmentTimeRequirement
      department: Command
      time: 3600 # 1 hour
    - !type:OverallPlaytimeRequirement
      time: 7200 #2 hrs # Bluespace-RoleTime
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess

- type: startingGear
  id: CaptainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCaptain
    back: ClothingBackpackCaptainFilled
    shoes: ClothingShoesBootsLaceup
    head: ClothingHeadHatCaptain
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    outerClothing: ClothingOuterArmorCaptainCarapace
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  innerclothingskirt: ClothingUniformJumpskirtCaptain
  satchel: ClothingBackpackSatchelCaptainFilled
  duffelbag: ClothingBackpackDuffelCaptainFilled